/**
 * Sync the repo's source-of-truth markdown into website/content/ (generated,
 * gitignored). Docusaurus never reads README/CHANGELOG/docs/ directly:
 *
 *   docs/**            -> content/**            (verbatim copy)
 *   README.md          -> content/intro.md      (frontmatter + link rewrites)
 *   CHANGELOG.md       -> content/changelog.md  (frontmatter + H1 strip)
 *   protocol.md        -> link rewrites (repo-relative -> site-relative)
 *   superpowers/*      -> _category_.json labels for the autogenerated sidebar
 *
 * Repo-relative links must be rewritten because content/ sits at a different
 * depth; links that only make sense in the git repo are unlinked instead.
 */
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = dirname(dirname(fileURLToPath(import.meta.url)));
const REPO = dirname(SITE);
const CONTENT = join(SITE, "content");

rmSync(CONTENT, { recursive: true, force: true });
mkdirSync(CONTENT, { recursive: true });
cpSync(join(REPO, "docs"), CONTENT, { recursive: true });

// README -> intro.md
// replaceAll, not replace: the README links to the same page more than once,
// and a half-rewritten link is a broken link in the site build.
const intro = readFileSync(join(REPO, "README.md"), "utf8")
	.replace(/^# omp A2A Bridge\n/, "")
	.replaceAll("](docs/protocol.md)", "](./protocol.md)")
	.replaceAll("](docs/testing.md)", "](./testing.md)")
	.replaceAll("](CHANGELOG.md)", "](./changelog.md)")
	.replaceAll("[LICENSE](LICENSE)", "LICENSE 文件");
writeFileSync(join(CONTENT, "intro.md"), `---\ntitle: 使用指南\nslug: /\n---\n\n${intro}`);

// CHANGELOG -> changelog.md
const changelog = readFileSync(join(REPO, "CHANGELOG.md"), "utf8").replace(/^# Changelog\n/, "");
writeFileSync(join(CONTENT, "changelog.md"), `---\ntitle: 变更日志\n---\n\n${changelog}`);

// protocol.md: repo-relative links -> site form
const protocolPath = join(CONTENT, "protocol.md");
writeFileSync(
	protocolPath,
	readFileSync(protocolPath, "utf8")
		.replace("[`src/server.ts`](../src/server.ts)", "`src/server.ts`")
		.replace("[README](../README.md)", "[README](./intro.md)"),
);

// historical design docs: nicer autogenerated sidebar category labels
for (const [folder, label] of [
	["specs", "设计规格"],
	["plans", "实施计划"],
]) {
	const dir = join(CONTENT, "superpowers", folder);
	mkdirSync(dir, { recursive: true });
	writeFileSync(join(dir, "_category_.json"), `${JSON.stringify({ label, collapsed: true }, null, 2)}\n`);
}

console.log("synced content ->", CONTENT);
