import { defineConfig } from "vitepress";
import { withMermaid } from "vitepress-plugin-mermaid";

// GitHub Pages deployment: Actions sets GITHUB_REPOSITORY="owner/repo".
// Derive base so one config serves both local preview (base "/") and the
// published project site (base "/repo/"). User-site repos get base "/".
const [owner, repo] = (process.env.GITHUB_REPOSITORY ?? "").split("/");
const onGitHubPages = Boolean(process.env.GITHUB_ACTIONS && owner && repo);
const isUserSite = repo === `${owner}.github.io`;
const base = onGitHubPages ? (isUserSite ? "/" : `/${repo}/`) : "/";

// Absolute origin for canonical/OG URLs: the published GitHub Pages host, or
// the local dev server. SEO tags need absolute URLs; relative ones are ignored
// by crawlers.
const ORIGIN = onGitHubPages ? `https://${owner}.github.io` : "http://localhost:5173";
const SITE_URL = `${ORIGIN}${base}`;
const SITE_NAME = "omp A2A Bridge";

// content/ is generated by scripts/sync.mjs from the repo's README_ZN.md,
// CHANGELOG.md and docs/ — never edit files under content/ directly.
export default withMermaid(
	defineConfig({
	title: "omp A2A Bridge",
	description: "把运行中的 omp 变成一个 Streamable HTTP MCP 服务器",
	lang: "zh-CN",
	base,

	// Static assets live in website/public (served at base), so the favicon
	// href carries the base prefix; the theme logo is resolved via withBase.
	head: [["link", { rel: "icon", href: `${base}img/favicon.svg` }]],
	srcDir: "content",
	cleanUrls: true,
	markdown: {
		// Repo docs are plain CommonMark carrying literal {braces} and
		// <angle-brackets>; VitePress never parses them as JSX, but keep
		// HTML inline so table/list markup in the docs renders.
		html: true,
	},
	// Per-page SEO: canonical, Open Graph, Twitter Card, and WebSite JSON-LD.
	// VitePress emits title/description/lang/viewport itself; these are the
	// signals it does not cover.
	transformHead({ pageData, siteData }) {
		const rel = pageData.relativePath.replace(/index\.md$/, "").replace(/\.md$/, "");
		const url = `${SITE_URL}${rel}`;
		const title = pageData.title ? `${pageData.title} | ${SITE_NAME}` : SITE_NAME;
		const desc = pageData.description || "把运行中的 omp 变成一个 Streamable HTTP MCP 服务器";
		const image = `${SITE_URL}img/logo.svg`;
		const ld = {
			"@context": "https://schema.org",
			"@type": "WebSite",
			name: SITE_NAME,
			description: desc,
			url,
			inLanguage: "zh-CN",
		};
		return [
			["link", { rel: "canonical", href: url }],
			["meta", { property: "og:type", content: "website" }],
			["meta", { property: "og:site_name", content: SITE_NAME }],
			["meta", { property: "og:title", content: title }],
			["meta", { property: "og:description", content: desc }],
			["meta", { property: "og:url", content: url }],
			["meta", { property: "og:image", content: image }],
			["meta", { property: "og:locale", content: "zh_CN" }],
			["meta", { name: "twitter:card", content: "summary" }],
			["meta", { name: "twitter:title", content: title }],
			["meta", { name: "twitter:description", content: desc }],
			["meta", { name: "twitter:image", content: image }],
			["script", { type: "application/ld+json", innerHTML: JSON.stringify(ld) }],
		];
	},
	themeConfig: {
		siteTitle: SITE_NAME,
		logo: "/img/logo.svg",
		nav: [
			{ text: "首页", link: "/" },
			{ text: "使用指南", link: "/intro" },
			{ text: "协议参考", link: "/protocol" },
			{ text: "测试与探针", link: "/testing" },
			{ text: "变更日志", link: "/changelog" },
		],
		sidebar: {
			"/": [
				{ text: "使用指南", link: "/intro" },
				{ text: "协议参考", link: "/protocol" },
				{ text: "测试与探针", link: "/testing" },
				{ text: "变更日志", link: "/changelog" },
				{
					text: "设计规格",
					collapsed: true,
					items: [
						{
							text: "A2A MCP Bridge 设计",
							link: "/superpowers/specs/2026-09-10-a2a-mcp-bridge-design",
						},
					],
				},
				{
					text: "实施计划",
					collapsed: true,
					items: [
						{
							text: "A2A MCP Bridge",
							link: "/superpowers/plans/2026-09-10-a2a-mcp-bridge",
						},
					],
				},
			],
		},
		socialLinks: [{ icon: "github", link: "https://github.com/adam-ikari/pi-a2a-ext" }],
		search: { provider: "local" },
		footer: {
			message: "基于 MIT 协议发布",
			copyright: "Copyright © omp A2A Bridge",
		},
	},
		mermaid: {},
	}),
);
