import { defineConfig } from "vitepress";

// GitHub Pages deployment: Actions sets GITHUB_REPOSITORY="owner/repo".
// Derive base so one config serves both local preview (base "/") and the
// published project site (base "/repo/"). User-site repos get base "/".
const [owner, repo] = (process.env.GITHUB_REPOSITORY ?? "").split("/");
const onGitHubPages = Boolean(process.env.GITHUB_ACTIONS && owner && repo);
const isUserSite = repo === `${owner}.github.io`;
const base = onGitHubPages ? (isUserSite ? "/" : `/${repo}/`) : "/";

// content/ is generated by scripts/sync.mjs from the repo's README_ZN.md,
// CHANGELOG.md and docs/ — never edit files under content/ directly.
export default defineConfig({
	title: "omp A2A Bridge",
	description: "把运行中的 omp 变成一个 Streamable HTTP MCP 服务器",
	lang: "zh-CN",
	base,

	// Static assets live in website/public (served at base), so the favicon
	// href carries the base prefix; the theme logo is resolved via withBase.
	head: [["link", { rel: "icon", href: `${base}img/favicon.svg` }]],
	srcDir: "content",
	cleanUrls: true,
	markdown: {
		// Repo docs are plain CommonMark carrying literal {braces} and
		// <angle-brackets>; VitePress never parses them as JSX, but keep
		// HTML inline so table/list markup in the docs renders.
		html: true,
	},
	themeConfig: {
		siteTitle: "omp A2A Bridge",
		logo: "/img/logo.svg",
		nav: [
			{ text: "首页", link: "/" },
			{ text: "使用指南", link: "/intro" },
			{ text: "协议参考", link: "/protocol" },
			{ text: "测试与探针", link: "/testing" },
			{ text: "变更日志", link: "/changelog" },
		],
		sidebar: {
			"/": [
				{ text: "使用指南", link: "/intro" },
				{ text: "协议参考", link: "/protocol" },
				{ text: "测试与探针", link: "/testing" },
				{ text: "变更日志", link: "/changelog" },
				{
					text: "设计规格",
					collapsed: true,
					items: [
						{
							text: "A2A MCP Bridge 设计",
							link: "/superpowers/specs/2026-09-10-a2a-mcp-bridge-design",
						},
					],
				},
				{
					text: "实施计划",
					collapsed: true,
					items: [
						{
							text: "A2A MCP Bridge",
							link: "/superpowers/plans/2026-09-10-a2a-mcp-bridge",
						},
					],
				},
			],
		},
		socialLinks: [{ icon: "github", link: "https://github.com/adam-ikari/pi-a2a-ext" }],
		search: { provider: "local" },
		footer: {
			message: "基于 MIT 协议发布",
			copyright: "Copyright © omp A2A Bridge",
		},
	},
});
