import { defineConfig, type Plugin } from "vitepress";
import { MermaidMarkdown } from "vitepress-plugin-mermaid";

// GitHub Pages deployment: Actions sets GITHUB_REPOSITORY="owner/repo".
// Derive base so one config serves both local preview (base "/") and the
// published project site (base "/repo/"). User-site repos get base "/".
const [owner, repo] = (process.env.GITHUB_REPOSITORY ?? "").split("/");
const onGitHubPages = Boolean(process.env.GITHUB_ACTIONS && owner && repo);
const isUserSite = repo === `${owner}.github.io`;
const base = onGitHubPages ? (isUserSite ? "/" : `/${repo}/`) : "/";

// Absolute origin for canonical/OG URLs: the published GitHub Pages host, or
// the local dev server. SEO tags need absolute URLs; relative ones are ignored
// by crawlers.
const ORIGIN = onGitHubPages ? `https://${owner}.github.io` : "http://localhost:5173";
const SITE_URL = `${ORIGIN}${base}`;
const SITE_NAME = "omp A2A Bridge";
// One description, used for config.description and as the per-page fallback in
// transformHead. Two copies drifted before: the site description said one thing
// and every og:description said another.
const SITE_DESC = "让任意 MCP 客户端调用本机 omp 会话里的工具，执行落在真实的文件与 shell 上，宿主不做模型推理";

// Mermaid settings, handed to the diagram component as a virtual module. This
// replaces withMermaid(), whose Vite plugin injected a *statically imported*
// Mermaid into the app entry — that put mermaid plus every diagram type in the
// entry's import graph, so all of it was fetched on every page including the
// four with no diagram. We keep the plugin's markdown fence (it emits the
// <Mermaid> tag) and register the component ourselves, async, in theme/index.ts.
const mermaidConfig = {
	securityLevel: "loose" as const,
	startOnLoad: false,
	theme: "default",
};

/** Serves `virtual:mermaid-config` for theme/Mermaid.vue. */
function mermaidSettingsPlugin(): Plugin {
	const id = "virtual:mermaid-config";
	const resolved = `\0${id}`;
	return {
		name: "a2a-mermaid-settings",
		resolveId: (source) => (source === id ? resolved : undefined),
		load: (source) => (source === resolved ? `export default ${JSON.stringify(mermaidConfig)}` : undefined),
	};
}

// content/ is generated by scripts/sync.mjs from the repo's README_ZN.md,
// CHANGELOG.md and docs/ — never edit files under content/ directly.
export default defineConfig({
	title: "omp A2A Bridge",
	description: SITE_DESC,
	lang: "zh-CN",
	base,

	// Static assets live in website/public (served at base), so the favicon
	// href carries the base prefix; the theme logo is resolved via withBase.
	head: [["link", { rel: "icon", href: `${base}img/favicon.svg` }]],
	srcDir: "content",
	cleanUrls: true,
	// The async Mermaid component above is what actually keeps the diagrams out
	// of the entry's import graph. This is the second line of defence: if some
	// future dependency puts a shared chunk back on the entry graph, keep it out
	// of the render-blocking preload set rather than let it delay first paint.
	shouldPreload: (link) => !link.includes("/chunks/"),
	markdown: {
		// Repo docs are plain CommonMark carrying literal {braces} and
		// <angle-brackets>; VitePress never parses them as JSX, but keep
		// HTML inline so table/list markup in the docs renders.
		html: true,
		// ```mermaid fences become a <Mermaid> component tag. The component
		// itself is registered async in theme/index.ts.
		config: (md) => MermaidMarkdown(md, { class: "mermaid" }),
	},
	// Per-page SEO: canonical, Open Graph, Twitter Card, and WebSite JSON-LD.
	// VitePress emits title/description/lang/viewport itself; these are the
	// signals it does not cover.
	transformHead({ pageData }) {
		const rel = pageData.relativePath.replace(/index\.md$/, "").replace(/\.md$/, "");
		const url = `${SITE_URL}${rel}`;
		const title = pageData.title ? `${pageData.title} | ${SITE_NAME}` : SITE_NAME;
		const desc = pageData.description || SITE_DESC;
		// Social platforms do not render SVG in og:image (Twitter/X, Facebook
		// and Slack all ignore it), so the card ships as a 1200x630 PNG. The
		// editable source is public/img/og.svg next to it.
		const image = `${SITE_URL}img/og.png`;
		// A WebSite node on a docs page misdescribes it: only the home page is
		// the site, the rest are articles. Declaring the right type per page
		// also lets the home page carry the search-action sitelinks search
		// engines use to offer a sitelinks search box.
		const isHome = pageData.relativePath === "index.md";
		const ld = isHome
			? {
					"@context": "https://schema.org",
					"@type": "WebSite",
					name: SITE_NAME,
					description: desc,
					url,
					inLanguage: "zh-CN",
					potentialAction: {
						"@type": "SearchAction",
						target: {
							"@type": "EntryPoint",
							urlTemplate: `${SITE_URL}?q={search_term_string}`,
						},
						"query-input": "required name=search_term_string",
					},
				}
			: {
					"@context": "https://schema.org",
					"@type": "TechArticle",
					headline: title,
					description: desc,
					url,
					inLanguage: "zh-CN",
					isPartOf: { "@type": "WebSite", name: SITE_NAME, url: SITE_URL },
				};
		return [
			["link", { rel: "canonical", href: url }],
			["meta", { property: "og:type", content: isHome ? "website" : "article" }],
			["meta", { property: "og:site_name", content: SITE_NAME }],
			["meta", { property: "og:title", content: title }],
			["meta", { property: "og:description", content: desc }],
			["meta", { property: "og:url", content: url }],
			["meta", { property: "og:image", content: image }],
			// Dimensions and alt are declared so consumers can lay the card out
			// before the image loads; without them the aspect ratio is unknown.
			["meta", { property: "og:image:width", content: "1200" }],
			["meta", { property: "og:image:height", content: "630" }],
			["meta", { property: "og:image:alt", content: `${SITE_NAME} — ${desc}` }],
			["meta", { property: "og:locale", content: "zh_CN" }],
			// summary_large_image, not summary: a 630px-tall card is rendered
			// full-bleed on both timelines, summary would shrink it to a square.
			["meta", { name: "twitter:card", content: "summary_large_image" }],
			["meta", { name: "twitter:title", content: title }],
			["meta", { name: "twitter:description", content: desc }],
			["meta", { name: "twitter:image", content: image }],
			// Third tuple element, NOT a key in the attrs object: VitePress renders
			// ["script", attrs, innerHTML] as <script ...>innerHTML</script>. With
			// innerHTML inside attrs it was serialized as an HTML attribute, so the
			// script body was empty and crawlers saw no structured data at all.
			["script", { type: "application/ld+json" }, JSON.stringify(ld)],
		];
	},
	themeConfig: {
		siteTitle: SITE_NAME,
		logo: "/img/logo.svg",
		nav: [
			{ text: "首页", link: "/" },
			{ text: "使用指南", link: "/intro" },
			{ text: "协议参考", link: "/protocol" },
			{ text: "与 computer use", link: "/computer-use" },
			{ text: "测试与核验", link: "/testing" },
			{ text: "变更日志", link: "/changelog" },
		],
		sidebar: {
			"/": [
				{ text: "使用指南", link: "/intro" },
				{ text: "协议参考", link: "/protocol" },
				{ text: "与 computer use 的区别", link: "/computer-use" },
				{ text: "测试与核验", link: "/testing" },
				{ text: "变更日志", link: "/changelog" },
				{
					text: "设计规格",
					collapsed: true,
					items: [
						{
							text: "A2A MCP Bridge 设计",
							link: "/superpowers/specs/2026-09-10-a2a-mcp-bridge-design",
						},
					],
				},
				{
					text: "实施计划",
					collapsed: true,
					items: [
						{
							text: "A2A MCP Bridge",
							link: "/superpowers/plans/2026-09-10-a2a-mcp-bridge",
						},
					],
				},
			],
		},
		socialLinks: [{ icon: "github", link: "https://github.com/adam-ikari/pi-a2a-ext" }],
		// The default theme's UI chrome ships in English; a zh-CN site that
		// leaves these alone reads as half-finished (English "Search" box,
		// "Not Found", "Previous page"). VitePress exposes each string.
		sidebarMenuLabel: "目录",
		returnToTopLabel: "回到顶部",
		skipToContentLabel: "跳到正文",
		darkModeSwitchLabel: "外观",
		lightModeSwitchTitle: "切换到亮色模式",
		darkModeSwitchTitle: "切换到暗色模式",
		docFooter: { prev: "上一页", next: "下一页" },
		outline: { label: "本页目录", level: [2, 3] },
		notFound: {
			title: "页面不存在",
			// The default is an English Kerouac quote. State what happened
			// instead of guessing at a cause the server cannot know.
			quote: "这个地址下没有 .md 文件。站点只有 8 个页面，都列在左侧。",
			linkText: "回到首页",
			linkLabel: "回到首页",
		},
		search: {
			provider: "local",
			options: {
				translations: {
					button: { buttonText: "搜索文档", buttonAriaLabel: "搜索文档" },
					modal: {
						displayDetails: "显示详细列表",
						resetButtonTitle: "清除查询",
						backButtonTitle: "关闭搜索",
						noResultsText: "没有找到结果：",
						footer: {
							selectText: "选择",
							selectKeyAriaLabel: "回车键",
							navigateText: "切换",
							navigateUpKeyAriaLabel: "向上箭头",
							navigateDownKeyAriaLabel: "向下箭头",
							closeText: "关闭",
							closeKeyAriaLabel: "Esc",
						},
					},
				},
			},
		},
		footer: {
			message: "MIT 协议。文档站由仓库文档生成，改动以仓库为准。",
			copyright: `Copyright © 2026 adam-ikari`,
		},
	},
	vite: { plugins: [mermaidSettingsPlugin()] },
});
