import type { Config } from "@docusaurus/types";

const config: Config = {
	title: "omp A2A Bridge",
	tagline: "把运行中的 omp 变成一个 Streamable HTTP MCP 服务器",
	url: "http://localhost:3000",
	baseUrl: "/",
	onBrokenLinks: "throw",
	// .md files are plain CommonMark: repo docs contain literal {braces} and
	// <angle-brackets> that must not be treated as JSX/JS expressions.
	markdown: {
		format: "detect",
	},
	i18n: {
		defaultLocale: "zh-cn",
		locales: ["zh-cn"],
	},
	presets: [
		[
			"classic",
			{
				blog: false,
				docs: {
					// Generated by scripts/sync.mjs from the repo's README.md,
					// CHANGELOG.md and docs/ — never edit files under content/ directly.
					path: "content",
					routeBasePath: "docs",
					sidebarPath: "sidebars.ts",
				},
				theme: {
					customCss: "src/css/custom.css",
				},
			},
		],
	],
	themeConfig: {
		colorMode: { respectPrefersColorScheme: true },
		navbar: {
			title: "omp A2A Bridge",
			items: [
				{ type: "doc", docId: "intro", label: "指南", position: "left" },
				{ type: "doc", docId: "protocol", label: "协议", position: "left" },
				{ type: "doc", docId: "testing", label: "测试", position: "left" },
				{ to: "/docs/changelog", label: "更新日志", position: "left" },
				{ to: "/", label: "首页", position: "right" },
			],
		},
		footer: {
			style: "dark",
			links: [
				{
					title: "文档",
					items: [
						{ label: "使用指南", to: "/docs/" },
						{ label: "协议参考", to: "/docs/protocol" },
						{ label: "测试与探针", to: "/docs/testing" },
					],
				},
				{
					title: "更多",
					items: [{ label: "变更日志", to: "/docs/changelog" }],
				},
			],
			copyright: "MIT License · omp A2A Bridge",
		},
	},
};

export default config;
