import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	docs: [
		"intro",
		"protocol",
		"testing",
		"changelog",
		{
			type: "category",
			label: "设计文档（历史存档）",
			collapsed: true,
			items: [{ type: "autogenerated", dirName: "superpowers" }],
		},
	],
};

export default sidebars;
